Translate Portugues pt-BR
node-red/node-red pull request #3100
Opened 2021-08-04 14:17 UTC by herickf

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Proposed changes

Create the Portuguese pt-BR translation following the standard and en files.

## Checklist

- [X] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2021-09-03 09:04 UTC, hardillb commented
@herickf I've just checked your commit and it was not made with the herick2008@gmail.com email address, but with the xxxxx@eletasolucoes.com.br address, you need to sign the CLA with the same email address that is attached to the commit.

2021-09-06 13:40 UTC, machadotiago requested changes
I fixed some translations and apart from that I have some comments: 
- The correct translation for payload, in this context, is "conteúdo", not "carga útil", but you cannot translate this term in some cases, specially when it is an example like "<code>payload</code>". I fixed it in **some** nodes like "Inject", "Change" and "Range" but there are more 60 other occurrences to be fixed, can you have a look on that?
- The word "Deletar" should be avoided, the correct term is "Remover", I think that I cover all occurrences in my comments.
- Great job :)

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +        "full": "Cheio",
Change to "Completo"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +        "title": "Event log",
Change to "Registro de eventos"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +        "view": "View log"
Change to "Visualizar eventos"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/messages.json
> +            "name": "mensagens de depuração",
Change to "Mensagens de depuração"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +            "current": "fluxo corrente",
Change to "fluxo atual"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +        "configDelete": "Deletar",
Change to "Remover"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +                "unmergedConfirm": "O branch local '__name__' tem alterações não mescladas que serão perdidas. Tem certeza que deseja deletar?",
Change to "O branch local '__name__' tem alterações não mescladas que serão perdidas. Tem certeza que deseja remover estas alterações?"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +                "deleteRemote": "Deletar remote"
Change to "Remover remoto"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +                "delete": "Deletar chave key",
Change to "Remover chave"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/messages.json
> +            "delete": "deletar file"
Change to "Remover arquivo"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/messages.json
> +            "deletefail": "falhou ao deletar o arquivo: __error__",
Change to "falhou ao remover o arquivo: __error__"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +                "grid": "Rede",
Change to "Grade"

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
> +        "compatModeDesc": "<h3> Modo de compatibilidade JSONata </h3> <p> A expressão atual parece ainda fazer referência a <code> msg </code>, então será avaliada no modo de compatibilidade. Atualiz
Change to:
`<h3> Modo de compatibilidade JSONata </h3> <p> A expressão atual parece ainda fazer referência a <code> msg </code>, então será avaliada no modo de compatibilidade. Atualize a expressão para não usar <code > msg </code>, pois este modo será removido no futuro. </p> <p> Quando o suporte JSONata foi adicionado pela primeira vez ao Node-RED, era necessária a expressão para fazer referência ao objeto <code> msg </code> . Por exemplo, <code> msg.payload </code> seria usado para acessar o conteúdo. </p> <p> Isso não é mais necessário, pois a expressão será avaliada em relação à mensagem diretamente. Para acessar a o conteúdo, a expressão deve ser apenas <code>payload</code>. </p>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +<p>Injeta uma mensagem em um fluxo manualmente ou em intervalos regulares. A mensagem
Change to 
`<p>Injeta uma mensagem em um fluxo manualmente ou em intervalos regulares. O conteúdo da`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +  a carga útil pode ser de vários tipos, incluindo strings, objetos JavaScript ou a hora atual.</p>
Change to:
`mensagem pode ser de vários tipos, incluindo strings, objetos JavaScript ou a hora atual.</p>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +    <dd>A carga configurada da mensagem.</dd>
Change to:
`    <dd>O conteúdo configurado da mensagem.</dd>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +<p>O nó Inject pode iniciar um fluxo com um valor de carga útil específico.
Change to:
`<p>O nó Inject pode iniciar um fluxo com um conteúdo específico.`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +A carga útil padrão é um carimbo de data / hora da hora atual em milissegundos desde 1º de janeiro de 1970. </p>
Change to:
`O conteúdo padrão é um estampa de data / hora da momento atual em milisegundos desde 1º de janeiro de 1970. </p>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/20-inject.html
> +<p> <b> Observação </b>: para incluir uma nova linha em uma string, você deve usar um nó de função para criar a carga útil. </p>
Change to:
`<p> <b> Observação </b>: para incluir uma nova linha em uma string, você deve usar um nó de função para alterar o conteúdo. </p>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/common/25-status.html
> + <p> Este nó não produz uma <code> carga útil </code>. </p>
Change to:
` <p> Este nó não produz um <code>payload</code>. </p>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/function/16-range.html
> +        <dt> carga útil <span class = "property-type"> número </span> </dt>
<dt>payload<span class = "property-type"> número </span> </dt>

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/function/16-range.html
> +        <dd> A carga útil <i> deve </i> ser um número. Qualquer outra coisa tentará ser
Change to:
`        <dd> O payload <i> deve </i> ser um número. Qualquer outra coisa tentará ser`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/function/16-range.html
> +        <dt> carga útil <span class = "property-type"> número </span> </dt>
Change to:
`        <dt> payload <span class = "property-type"> número </span> </dt>`

2021-09-06 13:40 UTC, machadotiago commented on packages/node_modules/@node-red/nodes/locales/pt-BR/function/80-template.html
> +carga útil: {
Change to:
`payload: {`

2021-09-06 17:29 UTC, FabsMuller commented
Herick anf Tiago, my .50 cents here. I just saw your pull request today. The work is quite good but in my opinion not for a pull request yet. Besides Tiago observations, there is still some fine tuning to do. So before submitting the PR, we could discuss a lit bit some translations in order to pr good work. If you don't mind I think we can improve and call others for help. For example in my opinion Carga útil is a correct translation for Payload because it really what the word means in PT and in Node-red.  I also saw "passphrase", "branch" and "remote" that could be translated to: frase de passe, Ramo e remote, but I didn't saw the whole work. Again it's a great work and a great start but let's discuss it before pr so we can submit a wonderful text. What do you think?

2022-07-25 22:18 UTC, FabsMuller commented
Hello Guys , just opened a new PR #3804 based on V.3.0.1 . I asked at Node-Red and Nick answered to submit a new PR to be more fresh to the lastest version. So this PR can be closed and lest work on the new one. Just to clear some thoughts, I'm very fan of Iberic (Portugal/Spain) approach of translating everything. So in the New PR you will find almost everything translated. Even if you don't agree or are not used to some of them, pls let's discuss it later. But I liked the results very much. Brgds.

2022-07-25 23:21 UTC, Steve-Mcl commented
Closing in favour of https://github.com/node-red/node-red/pull/3804

2022-07-25 23:21 UTC, closed without merging