Error on invalid encrypted credentials
node-red/node-red pull request #3498
Opened 2022-03-19 18:04 UTC by sammachin

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Fix for https://github.com/node-red/node-red/issues/3496
Also warn if using unencypted credentials 

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

2022-03-20 09:39 UTC, sammachin commented
Still working on why the tests fail,

2022-03-20 09:50 UTC, Steve-Mcl commented
>  fails

I think the runtime is empty Sam

https://github.com/node-red/node-red/blob/c7f48a83c0a5fa5f1dcd57415822b81899e98b3f/test/unit/%40node-red/runtime/lib/nodes/credentials_spec.js#L453

2022-03-21 15:56 UTC, Steve-Mcl commented on packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
> +            "encryptednotfound" : "Encrypted crededntials not found"
typo "crededntials"

2022-03-23 09:48 UTC, knolleary commented
The tests fail in `test/unit/@node-red/runtime/lib/nodes/index_spec.js` because it is hitting this code path, but the mocked runtime object does not include the `log._` function.

The fix is to modify:
https://github.com/node-red/node-red/blob/702545e0b238f160cce9b339808b230f9d741b08/test/unit/%40node-red/runtime/lib/nodes/index_spec.js#L66

to add a placeholder `_` function to the `log` object:

```
        log: {debug:function() {}, warn:function() {}, _: function() {}},
```

2022-03-23 09:50 UTC, knolleary requested changes

2022-03-23 09:50 UTC, knolleary commented on packages/node_modules/@node-red/runtime/lib/nodes/credentials.js
> +                    log.warn(log._("nodes.credentials.encryptednotfound"))
Either kebab-case or camelCase - never alllowercase
```suggestion
                    log.warn(log._("nodes.credentials.encryptedNotFound"))
```

2022-03-23 09:50 UTC, knolleary commented on packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
> +            "encryptednotfound" : "Encrypted credentials not found"
Either kebab-case or camelCase - never alllowercase
```suggestion
            "encryptedNotFound" : "Encrypted credentials not found"
```

2022-03-23 09:50 UTC, knolleary commented on packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
> +            "unencrypted" : "Using unecrypted credentials",
```suggestion
            "unencrypted" : "Using unencrypted credentials",
```

2022-03-24 08:44 UTC, sammachin commented
Thanks Nick, `npm test` now passes on my machine

2022-04-21 09:59 UTC, merged