Fix search type with spaces
node-red/node-red pull request #3841
Opened 2022-08-14 09:46 UTC by Steve-Mcl

fixes #3796

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Use quotes for type search to handle node names with a space

e.g. `type:debug` and `type:"mqtt out"` 

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2022-09-02 19:50 UTC, knolleary requested changes

2022-09-02 19:50 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/search.js
> +        console.log(`extractType(val, flags): val:${val}`)
```suggestion
```

2022-09-02 19:50 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/search.js
> +        val = extractType(val,flags);// uses:<node-id>
```suggestion
        val = extractType(val,flags);// type:<node-type>
```

2022-09-03 20:59 UTC, Steve-Mcl commented on packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
> +                }
```suggestion
                const wrapStr = function (str) {
                    if(str.indexOf(' ') >= 0) {
                        return '"' + str + '"'
                    }
                    return str
                }
```

2022-09-03 21:01 UTC, Steve-Mcl commented on packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
> +                }
fix linting "Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function"

2022-09-12 18:27 UTC, knolleary approved these changes

2022-09-12 18:27 UTC, merged