Add French translation of nodes
node-red/node-red pull request #3964
Opened 2022-11-29 19:58 UTC by GogoVega

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Add French translation of nodes.
Follows [PR#3962](https://github.com/node-red/node-red/pull/3962) (editor's translation).

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2022-12-04 09:31 UTC, Steve-Mcl commented
@GogoVega do you know any French speaking users in the community who can review your works?

Unfortunately we (I) are not fluent in french and cannot verify your translations.

V3.1 release is not too far off so the sooner we can get a French speaking reviewer the more chance your translations will be included in the release.

Thank you very much for your contributions.

2022-12-08 20:35 UTC, golfvert commented on packages/node_modules/@node-red/nodes/locales/fr/common/60-link.html
> +    <p>Créer des liens virtuelles entre les flux.</p>
<p>Créer des liens virtuels entre les flux.</p>

2022-12-08 20:39 UTC, golfvert requested changes
Just two minot editorial changes. Overall very good translation.

2022-12-08 20:39 UTC, golfvert commented on packages/node_modules/@node-red/nodes/locales/fr/common/90-comment.html
> +    <p>Le panneau d'édition acceptera la syntaxe Markdown. Le texte sera rendu dans
<p>Le panneau d'édition accepte la syntaxe Markdown.

2022-12-08 20:39 UTC, golfvert commented on packages/node_modules/@node-red/nodes/locales/fr/common/60-link.html
> +    <p>Créer des liens virtuelles entre les flux.</p>
<p>Créer des liens virtuels entre les flux.</p>

2022-12-08 20:55 UTC, GogoVega commented
@golfvert, thank you for your message and your work 🙂.

2023-01-13 13:32 UTC, GogoVega commented
Should I move the target branch from `master` to `dev`?

2023-01-13 13:36 UTC, knolleary commented
Hi - master is fine. Thank you all for the work on this. We'll get it merged in time for the 3.1-beta release

2023-03-03 15:18 UTC, merged