adding timeout attribute to function node
node-red/node-red pull request #4177
Opened 2023-05-22 08:20 UTC by k1ln

- [x] New feature (non-breaking change which adds functionality)

Discussion here: 
https://discourse.nodered.org/t/function-node-doesnt-have-timeout-feature/78483

## Proposed changes

Adding a timeout attribute to the function node, so an endless funciton doesnt break the node red server.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

2023-05-25 16:57 UTC, knolleary requested changes
Thanks for the PR @k1ln - I've retargeted it to the `dev` branch as this is where new feature development is done. This has pulled some extra commits in and made a bit of muddle of this PR. My apologies - but we'll sort it out in the merge.

The basic behaviour is good. I think there are a couple changes to make that I have proposed changes for inline:

1. Use seconds rather than milliseconds for the value. Millisecond precision feels unnecessary for this. Having the spinner increment by 1ms intervals felt like a lot of clicking to do anything meaningful :)
2. Use the input placeholder to show the units rather than the label. This is consistent with other core nodes.

LMK if you're happy with these changes and we can get them merged.

This *might* miss 3.1.0-beta.3, but will certainly be ready for the final 3.1.0 release.

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.js
> +        node.timeout = n.timeout*1;
```suggestion
        node.timeout = n.timeout*1000;
```

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.html
> +                max: 4294967294,
```suggestion
            // 4294967 is max in node.js timeout.
            $( "#node-input-timeout" ).spinner({
                min: 0,
                max: 4294967,
```

Change to second resolution.

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/locales/de/messages.json
> +            "timeout": "Timeout (ms)"
```suggestion
            "timeout": "Timeout"
```

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/locales/en-US/messages.json
> +            "timeout": "Timeout (ms)"
```suggestion
            "timeout": "Timeout"
```

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/locales/ru/messages.json
> +            "timeout":"Время ожидания (мс)"
```suggestion
            "timeout":"Время ожидания"
```

2023-05-25 16:57 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +        var flow = [{id:"n1",type:"function",wires:[["n2"]],timeout:"10",func:"while(1==1){};\nreturn msg;"}];
```suggestion
        var flow = [{id:"n1",type:"function",wires:[["n2"]],timeout:"0.010",func:"while(1==1){};\nreturn msg;"}];
```

2023-05-25 16:57 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.html
> +                <input id="node-input-timeout" style="width: 60px;" value="1000">
```suggestion
                <input id="node-input-timeout" style="width: 60px;" data-i18n="[placeholder]join.seconds">
```

Use a placeholder to indicate the units. This is consistent with other core nodes, such as the join node.

2023-05-26 13:04 UTC, k1ln commented
> Thanks for the PR @k1ln - I've retargeted it to the `dev` branch as this is where new feature development is done. This has pulled some extra commits in and made a bit of muddle of this PR. My apologies - but we'll sort it out in the merge.
> 
> The basic behaviour is good. I think there are a couple changes to make that I have proposed changes for inline:
> 
> 1. Use seconds rather than milliseconds for the value. Millisecond precision feels unnecessary for this. Having the spinner increment by 1ms intervals felt like a lot of clicking to do anything meaningful :)
> 2. Use the input placeholder to show the units rather than the label. This is consistent with other core nodes.
> 
> LMK if you're happy with these changes and we can get them merged.
> 
> This _might_ miss 3.1.0-beta.3, but will certainly be ready for the final 3.1.0 release.

Can we have a setting which could be used like default time to wait for a funciton node? I don't exactly know how I can get or populate the settings from the settings.js in the app directory to the frontend where the node is. Should i make a new PR for the dev branch for this one? 

Kind Regards 

Kilian

2023-05-26 13:25 UTC, Steve-Mcl commented
@k1ln from what I understand, this new feature, as it is currently implemented, shows an 0 value timeout by default (0 meaning no timeout)

I believe this is good enough for 1st version. It aligns with the current functionality pre V3.1 (as in no timeout by default). 

If you intend on implementing this, then I would suggest you branch off this branch and implement it as an extra feature. 

It may be that we have to wait until Node-RED v4 - as introducing a default value would be a (slightly) breaking change. That would of course need to be discussed on its merit and what that default value may look like.

2023-05-26 14:01 UTC, k1ln commented
@Steve-Mcl ok. Do you perhaps know how one can propagate settings from the settings.js to the frontend. The implementation is not exactly sharp cause if I just add stuff in the seeting.js file I don't have them available in the Frontend on the fly what i would expect. Where do i need to change something to propagate settings from the settings.js file to the frontend.

2023-05-26 14:46 UTC, Steve-Mcl commented
@k1ln 

Use [this doc](https://nodered.org/docs/creating-nodes/node-js#exposing-settings-to-the-editor) as a guide.


In essence: 

In `packages/node_modules/@node-red/nodes/core/function/10-function.js`, add 
```js
RED.nodes.registerType("function",FunctionNode, {
        dynamicModuleList: "libs",
        settings: {
            functionExternalModules: { value: true, exportable: true },
            functionTimeout: { value:30, exportable: true }, // << add
        }
    });
```


and in `packages/node_modules/node-red/settings.js`
![image](https://github.com/node-red/node-red/assets/44235289/399f4617-a063-4e15-ba53-051cc3be4979)

then you can access `RED.settings.functionTimeout` in both the `.js` and `.html`

2023-05-26 15:29 UTC, k1ln commented
@Steve-Mcl Thank you.

2023-05-26 20:51 UTC, dceejay commented
As long as the default remains 0 (=infinite as today) - then allowing a setting to re-configure it could be useful.
though I would call it `functionNodeTimeout` to make it explicitly about that node.

2023-05-30 12:27 UTC, Steve-Mcl commented
@k1ln could you rebase or merge dev into this branch and check there are no issues please?

2023-05-30 12:57 UTC, k1ln commented
@Steve-Mcl didn't knolleary ödo that before? I pushed that button now but now it says it needs approval.

2023-06-21 13:24 UTC, k1ln commented
@knolleary What do you mean? I resolved all your suggested changes above. Do i need to change anything more?

2023-06-21 13:25 UTC, knolleary commented
@k1ln ah - you clicked 'resolve' without accepting the changes I proposed. No matter - I'll redo them.

2023-06-21 13:27 UTC, hardillb commented
Just to be clear, clicking "Resolve" just closes the discussion, it does not change any code. You need to explicitly apply each of the suggested changes.

2023-06-21 13:28 UTC, knolleary commented
I have unresolved the conversations and applied the changes. Once the tests pass we can get this merged. Thanks @k1ln

2023-06-21 14:56 UTC, knolleary approved these changes

2023-06-21 14:57 UTC, merged

2023-06-21 19:28 UTC, k1ln commented
@knolleary Thank you next time i'll bei more careful.