Separate the "add new config-node" option into a new (+) button
node-red/node-red pull request #4627
Opened 2024-03-27 14:13 UTC by GogoVega

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This PR reduces the number of three steps into one to add a config-node by clicking a new (+) button.

The "edit" button will be disabled if no option is available. The "add" option is removed from the list as soon as it contains at least one option.

Requested by @joepavitt on the [forum](https://discourse.nodered.org/t/proposal-config-nodes/86629).

PS: I don't know if I should also adapt the test files? (`10-mqtt_page.js` and `22-websocket_page.js`)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2024-03-28 11:37 UTC, knolleary reviewed
Given the new button takes up horizontal space, making the select box narrower, I don't think we should also change the 'add new' message to push the type further to the right.

Also, by removing the `_ADD_` option from the select box if there are existing config nodes, it is no longer possible to leave the property unset. It forces you to pick an existing config node even if that isn't what you want it to do.

It may be an edge case, but being able to unset the value is something we should allow for.

2024-03-28 11:37 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
> +        "addNewType": "Please add new __type__...",
```suggestion
        "addNewType": "Add new __type__...",
```

2024-03-28 11:37 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/locales/fr/editor.json
> +    "addNewType": "Veuillez ajouter un nouveau __type__...",
```suggestion
    "addNewType": "Ajouter un nouveau __type__...",
```

2024-03-28 11:55 UTC, GogoVega commented
Do you want me to add a “nothing” option? So there will be 2 basic options (add and nothing) then the different options plus nothing?

2024-03-28 12:43 UTC, GogoVega commented
Something like that?

https://github.com/node-red/node-red/assets/92022724/99883f8a-8104-453d-b9eb-dd7b9bdcd6af

2024-03-28 14:51 UTC, knolleary commented
> Something like that?

... maybe... I'm not sure. It's one of the reasons this particular bit of UI has not received the update it has needed for so long. Trying to find the right UI that works for the different valid states it can be in.

I do agree having the `+` button is a good improvement. I'm going to have a play around to see what works.

2024-03-28 15:48 UTC, joepavitt commented
Just having a "None" option would work imo

2024-03-28 16:24 UTC, GogoVega commented
I am hesitating between the following for the case without options (no node available):
- "add new" (1 option) - the current
- "none" and "add new" (2 options)
- "add or leave blank" (1 option)

Then available options and "none" option.

2024-03-28 19:59 UTC, joepavitt commented
"None" _or_ "Add new..." make sense to me. Definitely not both together

2024-04-04 14:59 UTC, knolleary requested changes
Some minor changes to add a 'none' option, and add tooltips to the buttons

2024-04-04 14:59 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
> +        const editBtnId = `${prefix}-lookup-${property}`;
```suggestion
        const addBtnId = `${prefix}-btn-${property}-add`;
        const editBtnId = `${prefix}-btn-${property}-edit`;
```

2024-04-04 14:59 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
> +            .appendTo(outerWrap);
```suggestion
        RED.popover.tooltip(editButton, RED._('editor.editConfig', { type }));

        // create the add button
        const addButton = $('<a id="' + addBtnId + '" class="red-ui-button"><i class="fa fa-plus"></i></a>')
            .css({ "margin-left": "10px" })
            .appendTo(outerWrap);
        RED.popover.tooltip(addButton, RED._('editor.addNewConfig', { type }));
```

2024-04-04 14:59 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
> +                disableButton(editButton, true);
```suggestion
                disableButton(editButton, true);
            } else if (selectedOpt.val() === "") {
                disableButton(addButton, false);
                disableButton(editButton, true);
```

2024-04-04 14:59 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
> +                }
```suggestion
                } else {
                    select.append('<option value="">' + RED._("editor.inputs.none") + '</option>');
                }
```

2024-04-04 15:11 UTC, knolleary approved these changes

2024-04-04 15:11 UTC, merged