Add npm install timeout notification
node-red/node-red pull request #4662
Opened 2024-04-18 10:36 UTC by hardillb

part of https://github.com/node-red/node-red/issues/4622

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Adds a notification if the HTTP POST to install a new node is closed by a intermediate proxy (e.g. nginx)

![image](https://github.com/node-red/node-red/assets/1800845/1c125f8a-bd91-46d8-80de-d52a3d180fa9)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `npm run test` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2024-04-18 11:13 UTC, hardillb commented
I'm not sure why the test is failing, while it is in the node install space, it appears to be testing the backend, not the frontend, so should not be impacted by the changes.

2024-04-18 11:18 UTC, hardillb commented
OK, test passed when I rebased the branch on the dev branch

2024-04-18 12:50 UTC, knolleary requested changes
One small wording tweak, but otherwise, looks good.

2024-04-18 12:50 UTC, knolleary commented on packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
> +                "installTimeout": "<p>Install continuing the background, Nodes will appear in palette when complete.</p><p>Or you can monitor the install logs</p>",
```suggestion
                "installTimeout": "<p>Install continuing the background.</p><p>Nodes will appear in palette when complete. Check the log for more information.</p>",
```

I may be wrong, but I don't think we use 'you' in our messages. Have tweaked the wording to be a bit more inline with the other messages.

2024-04-23 21:44 UTC, knolleary approved these changes

2024-04-23 21:44 UTC, merged