added default timeout to function node (#1)
node-red/node-red pull request #4985
Opened 2024-12-09 20:15 UTC by vasuvanka

* added default timeout to function node

* added unit test to support defaultFunctionTimeout

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Here’s an updated PR comment reflecting the name change to `defaultFunctionTimeout`:  

---

https://github.com/node-red/node-red/issues/4976

This PR introduces the `defaultFunctionTimeout` parameter for the Function node, defined in seconds. The primary purpose of this setting is to prevent blocking code within function blocks from indefinitely halting execution.  

**Key Details:**  
- **Default Value**: `0` (indicating no timeout).  
- **Functionality**:  
  - Serves as a default safeguard against blocking operations, such as an infinite loop (`while(1){}`), which can block the main thread.  
  - Ensures system stability by unblocking such scenarios after the specified timeout duration.  
- **Precedence**: If `functionTimeout` is specified in the settings file, it overrides `defaultFunctionTimeout`.  

This enhancement aims to improve the resilience of the system by mitigating the risk of blocking code. Please review and share feedback if further clarity or adjustments are needed.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `npm run test` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

2024-12-10 11:03 UTC, dceejay requested changes
You need to set any setting for test within the test - not in the node. So the tests will also need to be updated.

2024-12-11 20:56 UTC, dceejay approved these changes

2025-06-06 10:29 UTC, knolleary approved these changes
Looks good. Three changes I'm going to apply before merging (spread across a few places so lots of proposed changes...)

1. Renaming to `globalFunctionTimeout` - to help distinguish from `functionTimeout` which would have been better named as `default...`.
2. Reduced the comment in the settings file
3. Removed `node.error(...)` call - the `done(err)` will get the error logged - we don't need to log it twice. Reverted the test changes to match.

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.js
> +                        finOpt.timeout = RED.settings.defaultFunctionTimeout * 1000
```suggestion
                    } else if (RED.settings.globalFunctionTimeout > 0){
                        finOpt.timeout = RED.settings.globalFunctionTimeout * 1000
```

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.js
> +                        opts.timeout = RED.settings.defaultFunctionTimeout * 1000
```suggestion
                    } else if (RED.settings. globalFunctionTimeout > 0){
                        opts.timeout = RED.settings. globalFunctionTimeout * 1000
```

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/@node-red/nodes/core/function/10-function.js
> +                        return done(err);
```suggestion
                        return done(err);
```

Calling `done(err)` will do the right thing with the logging

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/node-red/settings.js
> + *  - defaultFunctionTimeout
```suggestion
 *  - globalFunctionTimeout
```

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/node-red/settings.js
> +
```suggestion

    /**
     * The default timeout (in seconds) for all Function nodes.
     * Individual nodes can set their own timeout value within their configuration.
     */
    globalFunctionTimeout: 0,

```

2025-06-06 10:29 UTC, knolleary commented on packages/node_modules/node-red/settings.js
>      /** Default timeout, in seconds, for the Function node. 0 means no timeout is applied */
```suggestion
    /**
      * Default timeout, in seconds, for the Function node. 0 means no timeout is applied
      * This value is applied when the node is first added to the workspace - any changes
      * must then be made with the individual node configurations.
      * To set a global timeout value, use `globalFunctionTimeout`
     */
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    logEvents.should.have.length(2);
```suggestion
                    logEvents.should.have.length(1);
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    logEvents.should.have.length(2);
```suggestion
                    logEvents.should.have.length(1);
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    logEvents.should.have.length(2);
```suggestion
                    logEvents.should.have.length(1);
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    logEvents.should.have.length(2);
```suggestion
                    logEvents.should.have.length(1);
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +        RED.settings.defaultFunctionTimeout = 0.01;
```suggestion
        RED.settings.globalFunctionTimeout = 0.01;
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    should.equal(RED.settings.defaultFunctionTimeout, 0.01);
```suggestion
                    should.equal(RED.settings.globalFunctionTimeout, 0.01);
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    delete RED.settings.defaultFunctionTimeout;
```suggestion
                    delete RED.settings.globalFunctionTimeout;
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +        RED.settings.defaultFunctionTimeout = 0.02;
```suggestion
        RED.settings.globalFunctionTimeout = 0.02;
```

2025-06-06 10:29 UTC, knolleary commented on test/nodes/core/function/10-function_spec.js
> +                    delete RED.settings.defaultFunctionTimeout;
```suggestion
                    should.equal(RED.settings.globalFunctionTimeout, 0.02);
                    should.equal(msg.msg.message, 'Script execution timed out after 10ms');
                    delete RED.settings.functionTimeout;
                    delete RED.settings.globalFunctionTimeout;
```

2025-06-06 10:40 UTC, knolleary commented
Thanks for this - sorry it took a while to get it merged. Will be in 4.1

2025-06-06 10:40 UTC, merged